load("@pip_deps//:requirements.bzl", "requirement")

py_library(
    name = "templating_lib",
    srcs = [] + glob(["*.py"]),
    data = [],
    visibility = [
        "//:__subpackages__",
    ],
    deps = [],
)
