name: formatting check
on: [push, pull_request]
jobs:
  black_linter:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
