name: Security Audit
on: [push, pull_request]
jobs:
  bandit_check:
    name: runner / bandit auditor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tj-actions/bandit@v5
        with:
          targets: ./bottle_utils/src
